### PR TITLE
fix: The Render Object of element which set position may be at …

### LINKED ISSUE #1077: demo/dragable-list.js 无法拖动
### 使用的 Kraken 版本 ｜ What version of kraken are you using

main

### 重现步骤 ｜ Steps To Reproduce

列表无法拖动

**重现代码 | Code example:** 

https://kraken.oss-cn-hangzhou.aliyuncs.com/demo/dragable-list.js

### PR DESCRIPTION
**Pull request by answershuto**
close #1077

### CODE REVIEW

**Review by andycall — DISMISSED** [review]

File: integration_tests/specs/dom/events/touchEvent.ts [hunk 1]
```diff
@@ -172,7 +172,20 @@ describe('TouchEvent', () => {
...
+
+  it('touchmove should work on body when element with position', async (done) => {
+    const div = document.createElement('div');
+    div.style.width = '100px';
+    div.style.height = '100px';
+    div.style.backgroundColor = 'red';
+    div.style.position = 'fixed';
+    document.body.appendChild(div);
+
+    window.addEventListener('touchmove', () => done())
```
Comment (temper357) [inline integration_tests/specs/dom/events/touchEvent.ts:187]: 这里的事件应该是关联到 document.body

**Review by temper357 — APPROVED** [review]

**Review by andycall — APPROVED** [review]
